# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ec06cc05223016dfded77db4346c3d49"
name = "Conversion Booster"
application_url = "https://conversion-booster-production.up.railway.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks"
  topics = [ "app/uninstalled" ]

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://conversion-booster-production.up.railway.app/webhooks"
  customer_data_request_url = "https://conversion-booster-production.up.railway.app/webhooks"
  shop_deletion_url = "https://conversion-booster-production.up.railway.app/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [
  "https://conversion-booster-production.up.railway.app/auth/callback",
  "https://conversion-booster-production.up.railway.app/auth/shopify/callback",
  "https://conversion-booster-production.up.railway.app/api/auth/callback",
  "http://localhost/auth/callback",
  "http://localhost/auth/shopify/callback"
]

[pos]
embedded = false
